# This is a basic workflow to help you get started with Actions

name: Auto Sync Fork&Push To Aliyun Oss

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    # Runs at 12:00, every 5 days
    - cron: '0 12 1/7 * ?'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sync_with_upstream"
  sync_with_upstream:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Sync main with upstream latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Step 1: run a standard checkout action, provided by github
      - name: Checkout main
        uses: actions/checkout@master

      # Step 1: run sync action
      - name: Fork Sync
        uses: tgymnich/fork-sync@v2.0.10
        with:
         base: main
         head: main

      # Step 3: run push to aliyun ossutil action push files to Aliyun oss
      - name: Push To Aliyun OSS
        uses: yizhoumo/setup-ossutil@v2.0.0
        with:
          # The version to download and use, or 'latest' for the latest version.
          ossutil-version: 'latest'
          
          # The following parameters are (optionally) used to config the credential.
          # The endpoint of the region in which the bucket is located.
          endpoint: "oss-cn-shanghai.aliyuncs.com"
          # The AccessKey ID of the credential.
          access-key-id: ${{secrets.OSS_ACCESS_KEY}}
          # The AccessKey Secret of the credential.
          access-key-secret: ${{secrets.OSS_ACCESS_KEY_SECRET}}
      - run: ossutil cp --only-current-dir -r -u ./ oss://chino-public/BTN-Collected-Rules/ --include "*.txt"
      - run: ossutil cp --only-current-dir -r -u ./combine/ oss://chino-public/BTN-Collected-Rules/ --include "*.txt"

      # Step 4: Print a helpful timestamp for your records (not required, just nice)
      - name: Timestamp
        run: date
